<#import "common.ftlh" as c>
<@c.page>
    <div class="container-fluid">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus alias, consequatur corporis culpa, deleniti
        deserunt esse, exercitationem facilis id ipsam maiores minus molestias non odio odit omnis praesentium quo
        recusandae repellat sequi soluta suscipit unde voluptate. Adipisci id laboriosam nostrum.
    </div>
</@c.page>
